platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.0.4
    username: ((docker-hub-username))
    password: ((docker-hub-password))
params:
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  DEPLOY_ENVIRONMENT: build
  NOTIFY_API_KEY: ((build-notify-api-key))
  DNS_DEPLOYER_ROLE_ARN: ((deployer-role-arn-production))
  DNS_STATE_BUCKET: ((dns-state-bucket))
  DNS_STATE_KEY: ((dns-state-key))
inputs:
  - name: api-src
  - name: oidc-api-release
  - name: frontend-api-release
  - name: client-registry-api-release
outputs:
  - name: terraform-outputs
run:
  path: /bin/sh
  args:
    - -euc
    - |
      cd "api-src/ci/terraform/shared"
      terraform init -input=false \
        -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
        -backend-config "bucket=digital-identity-dev-tfstate" \
        -backend-config "key=${DEPLOY_ENVIRONMENT}-shared-terraform.tfstate" \
        -backend-config "encrypt=true" \
        -backend-config "region=eu-west-2"

      terraform apply -auto-approve \
        -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
        -var "environment=${DEPLOY_ENVIRONMENT}" \
        -var 'logging_endpoint_enabled=true' \
        -var 'logging_endpoint_arn=arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prod' \
        -var-file ${DEPLOY_ENVIRONMENT}-stub-clients.tfvars \

      terraform output --json > ../../../../terraform-outputs/${DEPLOY_ENVIRONMENT}-shared-terraform-outputs.json
