name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Spotless
        run: ./gradlew --no-daemon spotlessCheck


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Run Build
        run: ./gradlew --parallel build -x test -x account-management-integration-tests:test -x spotlessApply -x spotlessCheck

  run-unit-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Run Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --parallel test jacocoTestReport -x integration-tests:test -x account-management-integration-tests:test -x spotlessApply -x spotlessCheck
      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: unit-test-reports
          path: |
            */build/reports/
            !integration-tests/build/reports/
            !account-management-integration-tests/build/reports/

          retention-days: 5
      - name: Cache Unit Test Reports
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-unit-test-reports-${{ github.sha }}
          path: |
            */build/jacoco/
            */build/reports/
            !integration-tests/build/jacoco/
            !integration-tests/build/reports/
            !account-management-integration-tests/build/jacoco/
            !account-management-integration-tests/build/reports/

  run-integration-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Run Integration Tests
        run: |
          ./gradlew :integration-tests:test :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck
      - name: Upload Integration Test Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: integration-test-reports
          path: integration-tests/build/reports/tests/test/
          retention-days: 5
      - name: Run Account Management Integration Tests
        run: |
          ./gradlew :account-management-integration-tests:test :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck
      - name: Upload Account Management Integration Test Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: account-management-integration-test-reports
          path: account-management-integration-tests/build/reports/tests/test/
          retention-days: 5
      - name: Upload Docker Container Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: docker-container-logs
          path: logs/
          retention-days: 5
      - name: Stop Services
        if: always()
        run: |
          ./gradlew --no-daemon :composeDownForced
      - name: Cache Test Reports
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-integration-test-reports-${{ github.sha }}
          path: |
            integration-tests/build/jacoco/
            integration-tests/build/reports/
            account-management-integration-tests/build/jacoco/
            account-management-integration-tests/build/reports/

  run-sonar-analysis:
    runs-on: ubuntu-latest
    needs:
      - run-unit-tests
      - run-integration-tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Cache Unit Test Reports
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-unit-test-reports-${{ github.sha }}
          path: |
            */build/jacoco/
            */build/reports/
            !integration-tests/build/jacoco/
            !integration-tests/build/reports/
            !account-management-integration-tests/build/jacoco/
            !account-management-integration-tests/build/reports/
      - name: Cache Test Reports
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-integration-test-reports-${{ github.sha }}
          path: |
            integration-tests/build/jacoco/
            integration-tests/build/reports/
            account-management-integration-tests/build/jacoco/
            account-management-integration-tests/build/reports/
      - name: Run SonarCloud Analysis
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info -x test -x account-management-integration-tests:test -x spotlessApply -x spotlessCheck
