name: Pre-merge checks for Account Management
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - 'account-management-api'
      - 'account-management-integration-tests'
      - 'ci/terraform/account-management/**'
      - 'ci/terraform/modules/account-management-endpoint-module/**'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: ./gradlew build -x integration-tests:test -x account-management-integration-tests:test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Integration Tests
        run: ./pre-commit.sh -tg